"""initial migrate

Revision ID: 8c48ab7580a8
Revises: 
Create Date: 2023-11-29 11:50:55.068366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c48ab7580a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('real_estate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('author_type', sa.String(length=64), nullable=True),
    sa.Column('link', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('deal_type', sa.String(length=64), nullable=True),
    sa.Column('accommodation_type', sa.String(length=64), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('floors_count', sa.Integer(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=True),
    sa.Column('total_meters', sa.Float(), nullable=True),
    sa.Column('price_per_m2', sa.Integer(), nullable=True),
    sa.Column('price_per_month', sa.Integer(), nullable=True),
    sa.Column('commissions', sa.Integer(), nullable=True),
    sa.Column('district', sa.String(length=64), nullable=True),
    sa.Column('street', sa.String(length=64), nullable=True),
    sa.Column('house_number', sa.String(length=64), nullable=True),
    sa.Column('underground', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('real_estate')
    # ### end Alembic commands ###
